#!/bin/bash

export PATH=/home/adi/bin:$PATH

TL=${1}
YESTERDAY_FLAG=${2}

if [ -z ${YESTERDAY_FLAG} ]
then
    DAY=$(date +%Y%m%d)
else
    DAY=$(date --date="yesterday" +%Y%m%d)
fi

PICS_DIR=/speed/timelapse/${TL}

echo Making timelapse for day ${DAY}...

cd ${PICS_DIR}/${DAY}*

# E.g. extract 20180303-102218 from ${PICS_DIR}/20180303-102218
dirname=${PWD##*/}

# Extract date - e.g. 20180303 from 20180303-102218
date=${dirname%*-*}

TIMELAPSE=SGW_${date}

# Step 1
#time tl_rotate_one_by_one

# Step 2
time tl_timestamp

#pwd
#exit

# Step 3
time (tl_encode_timelapse ${TIMELAPSE} 2> /dev/null)

/bin/mv ${TIMELAPSE}.avi ${PICS_DIR}/../${TL}_done

cd ~

# Remove the photos
/bin/rm -rf ${PICS_DIR}/${DAY}*

echo
echo Done.
