#!/bin/bash

ulimit -c 0

for image in `ls -1 *.jpg`; do

  #
  # Rotate righ: mogrify -rotate "90"
  # Rotate left: mogrify -rotate "-90" 
  #
  mogrify -rotate "90" ${image} 2> /dev/null

  if [ $? -eq 0 ]
  then
    #echo -e "Rotated ${image}."
    :
  else
    echo -e "ERROR: Failed rotating $image. Deleting."
    /bin/rm ${image} ${image}~
  fi

done
